### ISSUE TITLE
Google-Maps full sdk options

### ISSUE THREAD

**Issue by halie412** [ionic-team/capacitor-plugins#1090]
## Feature Request
Hi how many time you think would take to implement the most of options in Google Maps SDK like: Shapes, Polygons, Circles, Update marker option and more...

### Plugin
google-maps

### Description
Actual plugin options aren´t full offer of Google Maps SDK

### Platform(s)
iOS 
Android
Web (if is possible like anothers plugin using Javascript SDK)

### Preferred Solution
Any solution is fine

### Alternatives
No, since is an SDK

### Additional Context
I think on current production version is limited and basic the functionality

**Comment by jcesarmobile** [comment]
We don't know when all SDK features will be available, if you want any specific feature to be included create a specific issue for it, having a "full SDK" issue is not helpful since the native SDKs also evolve and can include more options in the future, so I'm going to close this issue.
Feel free to create issues for specific features that are not supported yet, but use the search first as there are a few feature requests already.
