### ISSUE TITLE
Local notification and push notification sound stopped working after migration

### ISSUE THREAD

**Issue by ThinkinDragon** [ionic-team/capacitor-plugins#1105]
## Bug Report

after migrating to v4.0 
Local notification and firebase notification sound stopped working 
was working fine with v3

### Plugin(s)
       @capacitor-community/stripe@3.9.1
       @capacitor/app@4.0.0
       @capacitor/device@4.0.0
       @capacitor/geolocation@4.0.0
       @capacitor/google-maps@4.0.0
       @capacitor/local-notifications@4.0.0
       @capacitor/push-notifications@4.0.0
       @capacitor/share@4.0.0

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.0.0
  @capacitor/android: 4.0.0
  @capacitor/core: 4.0.0

### Platform(s)
android for now

### Current Behavior
even after change importance to 5, the sound is not coming 

### Code Reproduction

```
import { LocalNotifications } from "@capacitor/local-notifications";
import { defineStore } from "pinia";
import { Capacitor } from "@capacitor/core";

export const useLocalNotification = defineStore("notification", {
  persist: true,
  state: () => ({
    token: "",
    notification: null,
    notificationList: null,
    processing: false,
  }),
  getters: {
    getToken(state) {
      return state.token;
    },
  },
  actions: {
    reset(state) {
      state.$reset();
    },

    async addLocalNotificationListeners() {
      await LocalNotifications.addListener("registration", (token) => {
        console.info("Registration token: ", token.value);
        this.token = token.value;
      });

      await LocalNotifications.addListener("registrationError", (err) => {
        console.error("Registration error: ", err.error);
      });

      await LocalNotifications.addListener("pushNotificationReceived", (notification) => {
        console.log("Push notification received: ", notification);
        this.notification = notification;
      });

      await LocalNotifications.addListener("pushNotificationActionPerformed", (notification) => {
        console.log("Push notification action performed", notification.actionId, notification.inputValue);
        this.notification = notification;
      });
    },

    async registerLocalNotifications() {
      let permStatus = await LocalNotifications.checkPermissions();

      if (permStatus.receive === "prompt") {
        permStatus = await LocalNotifications.requestPermissions();
      }

      if (permStatus.receive !== "granted") {
        throw new Error("User denied permissions!");
      }

      await LocalNotifications.register();
    },

    async getDeliveredNotifications() {
      this.notificationList = await LocalNotifications.getDeliveredNotifications();
      console.log("delivered notifications", notificationList);
    },
    async sendLocal(title,body,id) {
      LocalNotifications.schedule({
        notifications: [{
            title: title,
            body: body,
            id: id,
            attachments: null,
            actionTypeId: "",
            extra: null,
            sound:'beep.wav',
            importance:5,
            // trigger: {
            //     at: new Date(Date.getTime() + (1000 * 1))
            // },
        }]
    })
    },
    async sendSoundLocal(title,body,id) {
      LocalNotifications.schedule({
        notifications: [{
            title: title,
            body: body,
            id: id,
            attachments: null,
            actionTypeId: "",
            extra: null,
            sound:'alert_tone.wav',
            importance:5,
            // trigger: {
            //     at: new Date(Date.getTime() + (1000 * 1))
            // },
        }]
    })
    }
  },
});

```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ThinkinDragon** [comment]
hi sorry for delay ,
I was able to get the notification back successfully but no sound work now in any android version the sample sound are in the resources folder 
[code Reproduced](https://github.com/ThinkinDragon/nuxt-capacitor-notification-issue).

**Comment by ThinkinDragon** [comment]
hi, the files are added, kindly check the app only support only one sound multiple sound don't work like native sound files are placed in raw folder

**Comment by jcesarmobile** [comment]
So you are saying that one sound is working, but not multiple sounds?

That's expected, check the docs for sound parameter in the notification schema

> * Only available for iOS and Android < 26.
> * For Android 26+ use channelId of a channel configured with the desired sound.

https://capacitorjs.com/docs/apis/local-notifications#localnotificationschema

In my testing, on an Android 6 device (SDK < 26) both sounds are working.
On my Android 12 device (SDK >= 26) only `alert_tone.wav` is working because that's the default sound configured in `capacitor.config.json` file as default sound.

On Android >= 26 if you want multiple sounds you have to create multiple channels with different sounds configured and on the notification schema use the `channelId` property to choose the desired channel with the sound you want to play. `alert_tone.wav` is working because on app install a default channel is created with the configured sound and if you don't specify a channel then the default channel will be used and with it the default sound will play.

Note that users can change the channel sounds in the app settings, so on Android >= 26 there is no guarantee that the sound you programmed will be played.

**Comment by ThinkinDragon** [comment]
so in place of direct calling schedule i need to make multiple Channel on register of notification. and call them with channel id, can chanelId be static or predefined?
then i can play separate sound 
is it possible to make run sound in background in app as we trigger it with WS pragmatically

**Comment by jcesarmobile** [comment]
You have to create the channels by calling `createChannel` before calling schedule so when you call schedule the channel already exists and you can use  the `chanelId`, you can create all of them on first app launch or just a channel with a sound right before calling schedule, that's up to you.
`chanelId` has to match the `id` param you used on the `createChannel` call, so can be static or predefined, depends on your code and how you want to do the `createChannel` calls.

I don't really understand the last question. 
If you schedule a notification it will fire even if the app is in background and the sound will play.
If what you want is to play a sound when the notification is fired programmatically instead of using the notification sound, not really sure if it will play, but you can add the `localNotificationReceived` listener to execute code when the notification is fired
```
LocalNotifications.addListener("localNotificationReceived", function() {
// play custom sound here, but not sure if will work in background
});
```
