### ISSUE TITLE
appStateChange on iOS return true when notifications center is open [@capacitor/app]

### ISSUE THREAD

**Issue by RRGT19** [ionic-team/capacitor-plugins#1132]
### Plugin(s)
- "@capacitor/app": "^1.1.1"

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/ios: 3.6.0
```

### Platform(s)
- iOS

### Current Behavior
When using `App.addListener('appStateChange', listenerFunc)`, I receive `true` when the notifications center is open.

### Expected Behavior
When notifications center is open, a `false` should be returned because the app is not what you are seeing.

### Code Reproduction
```
App.addListener('appStateChange', event => {
 // event.value is true when notifications center is open
})
```

### Additional Context

**When I open the notifications center:**

![image](https://user-images.githubusercontent.com/33521443/184982369-6f6cdcee-6d7f-43b3-883b-36a6cc846dc3.png)

**When I close the notifications center:**

![image](https://i.ibb.co/0FWMmhD/Screen-Shot-2022-08-16-at-4-49-38-PM.png)

**Comment by jcesarmobile** [comment]
appStateChange fires with true whenever the native `UIApplication.didBecomeActiveNotification` fires, and fires with false if `UIApplication.willResignActiveNotification` fires. 
When as soon as you start showing notification center `willResignActiveNotification` is fired, and then if you make it full screen it fires `didBecomeActiveNotification` and then `willResignActiveNotification` again.
Sadly there is nothing we can do about it, it's the native events the ones reporting wrong information, so it should be reported to Apple as only them can fix the issue.

We could check the `UIApplication.shared.applicationState` value, but sadly, when showing notification center the actual status is always active since the app is still open and running under the notification center screen, it would only switch to inactive if something interrupts the app like a phone call or turning off the screen, but notification center isn't doing that.

We have another issue about improving/adding more states, so I'm closing this one in favour of the other one
https://github.com/ionic-team/capacitor-plugins/issues/1153
