### ISSUE TITLE
(android) Splash Screen stretched in Android API 30

### ISSUE THREAD

**Issue by dragermrb** [ionic-team/capacitor-plugins#1159]
## Bug Report
Splash screen is stretched in android API 30 on emulator Pixel 5 (1080x2340)

### Plugin(s)
- @capacitor/splash-screen

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/core: 4.1.0

[success] Android looking great! 👌
```

### Platform(s)
- @capacitor/android: 4.1.0
- Emulator Pixel 5 API 30 1080x2340

### Current Behavior
Image vertically stretched
![Screenshot_20220829_121947](https://user-images.githubusercontent.com/11479696/187180596-6545ea8b-c602-45dc-9cce-e2c05406f79e.png)

### Expected Behavior
Image not stretched

### Code Reproduction
```sh
ionic start test-splash blank --capacitor
npm install @capacitor/app @capacitor/haptics @capacitor/keyboard @capacitor/status-bar
npm install @capacitor/splash-screen
npm run build
npx cap sync
```
capacitor.config.json
```json
{
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 5000,
      "backgroundColor": "#00ffffff",
      "androidScaleType": "CENTER_CROP"
    }
  }
}
```

**Comment by jcesarmobile** [comment]
Capacitor no longer handles the displaying of the initial splash screen (other than the delay), it leverages into the Android 12 Splash Screen API and the AndroidX support library for it.
You can report the issue to google or switch to using a splash icon instead of a full screen background image
https://developer.android.com/develop/ui/views/launch/splash-screen

**Comment by dragermrb** [comment]
Hi @jcesarmobile 

So options like `androidScaleType` are useless now?

```json
{
  "plugins": {
    "SplashScreen": {
      "androidScaleType": "CENTER_CROP",
    }
  }
```

**Comment by jcesarmobile** [comment]
Yeah, most configuration options are useless now when using the new Android 12 Splash Screen API, the docs have been updated and specify it, every option that is no longer supported says something like "Doesn't work on launch when using the Android 12 API.".

If you want to go back to the old behavior, you can disable the Android 12 Splash Screen API for Android < 12 (SDK < 31) by changing `Theme.SplashScreen` to `AppTheme.NoActionBar` on the `AppTheme.NoActionBarLaunch` style.
The Android 12 Splash Screen API can't be disabled for SDK 31+ devices, but they show the splash icon instead of the splash background, so the stretching doesn't affect them.

**Comment by dragermrb** [comment]
Thank you very much @jcesarmobile !
