### ISSUE TITLE
After Capacitor 4 upgrade, Splashscreen not working anymore on android API 30 or less

### ISSUE THREAD

**Issue by cyril-colin** [ionic-team/capacitor-plugins#1163]
### Plugin(s)
```json
"@capacitor/splash-screen": "^4.0.0"
```

### Capacitor Version
```
PASTE OUTPUT HERE
```

### Platform(s)
- android <= api 30

### Current Behavior
Since I updated my app to Capacitor 4 following the [documentation](https://capacitorjs.com/docs/updating/4-0), my android 11 splashscreen doesn't appears anymore.

### Expected Behavior
Despite the upgrade to Capacitor 4, my splash screen should be visible on startup of my app.
Expected steps:
- start app
- show a background color
- show a splashscreen

### Code Reproduction
Here is my configuration:
```ts
plugins: {
        SplashScreen: {
            androidSplashResourceName: 'new_splash', // this file is here : res/drawable-xxxhdpi/new_splash.png
res/drawable-xxxhdpi/new_splash.png
            showSpinner: false,
            androidScaleType: 'CENTER_CROP',
            backgroundColor: '#00ACD9',
            launchAutoHide: true,
            launchShowDuration: 10000,
        },
```
And my styles.xml

```xml
<style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
        <item name="android:background">@color/colorPrimary</item>
    </style>
```

### Additional Context
This issue may be related to https://github.com/ionic-team/capacitor-plugins/issues/1159 . I don't want to stay in the old way to deal with splashscreen, but I think I am missing some point about the update of Splashscreen plugin :/

Thanks for your help !

**Comment by jcesarmobile** [comment]
If you want to keep using `androidSplashResourceName` (and almost any other of the configurations you are using) you have to use the old splash screen, none of those are supported by the new Android 12 Splash Screen API, it doesn't let us configure anything programmatically, everything has to be configured from the `AppTheme.NoActionBarLaunch` style entry following https://developer.android.com/develop/ui/views/launch/splash-screen. `android:background` also works despite it's not listed there, but only for Android < 12, but you are using a color instead of an image. 

You can try to change the `<item name="android:background">@color/colorPrimary</item>` to `<item name="android:background">@drawable/new_splash</item>` and that should show the same image you are using, but probably stretched.
