### ISSUE TITLE
dynamic splash screens

### ISSUE THREAD

**Issue by scr2em** [ionic-team/capacitor-plugins#1266]
### Plugin
Splash Screen

### Description
is it possible to have multiple splash screens and based on the user's email we change the splash screen ? 

### Platform(s)
iOS and Android

### Preferred Solution
empty

### Alternatives
empty

**Comment by jcesarmobile** [comment]
No, it's not possible.
On iOS the splash screen plugin shows the configured Launch Storyboard, which is configured at project level in the Info.plist and there can be only one.
On Android it's also configured at project level on the AndroidManifest.xml and styles.xml

**Comment by scr2em** [comment]
@jcesarmobile hmm I can't even add multiple storyboards and based on a value in the keychain, we launch the corresponding storyboard ? I'm just wondering if there is any workaround for this .

**Comment by jcesarmobile** [comment]
No, The launch storyboard is shown before your app starts executing in order to provide a transition from the Springboard to your app while it is loading.
You could create your custom implementation of a splash screen plugin that shows a custom image with any logic you want, but the launch storyboard will still display first and for an unknown amount of time, then it would transition to your custom splash screen.
