### ISSUE TITLE
feat(Device): Get the device's current language on application level

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/capacitor-plugins#1291]
### Plugin
Device

### Description
Currently we can only detect the system language via Capacitor Device. However, for Android and IOS it is possible to set a different language on application level.

### Platform(s)
IOS and Android

### Preferred Solution
extend Device by Methods:

- `getApplicationLanguageCode()` - Get the device's current language locale code on application level
- `getApplicationLanguageTag()` - Get the device's current language locale tag on application level

### Alternatives
Not possible at the moment

**Comment by jcesarmobile** [comment]
How do you do that?
As far as I know, iOS allows to specify which languages the app supports, and a default development language of the project (`CFBundleDevelopmentRegion` key in the Info.plist), but not set a different language from the app nor get that. value.

On Android it's now possible, but starting on Android 13, and can be made backward compatible with `androidx.appcompat:appcompat` version 1.6.0-beta01, but there is no 1.6.0 final version yet. And I think I tested and `getLanguageCode` then returned the application language instead of the device language.

**Comment by DwieDima** [comment]
> How do you do that? As far as I know, iOS allows to specify which languages the app supports, and a default development language of the project (`CFBundleDevelopmentRegion` key in the Info.plist), but not set a different language from the app nor get that value.
> 
> On Android it's now possible, but starting on Android 13, and can be made backward compatible with `androidx.appcompat:appcompat` version 1.6.0-beta01, but there is no 1.6.0 final version yet. And I think I tested and `getLanguageCode` then returned the application language instead of the device language.

If you navigate to app settings, you can select preferred language (at least on simulator).
I haven't tested on android, but if `getLanguageCode ` returns application language instead, its perfect :)

<img width="360" alt="image" src="https://user-images.githubusercontent.com/26873275/202700155-81f8a2e6-1275-4d21-9492-33281917a2bc.png">
