### ISSUE TITLE
Camera plugin for iOS always prompts for permissions, confusing behavior when limited library is selected

### ISSUE THREAD

**Issue by chudooder** [ionic-team/capacitor-plugins#1297]
### Plugin(s)

Observed on:

```
@capacitor/camera: 4.1.4
```

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0
```

### Platform(s)

Observed on iOS 15.6 - iPhone X

### Current Behavior

After a fresh install of my app, the user clicks a button that calls `Camera.getPhoto`. The user is prompted to either select a photo or take a picture (expected due to `CameraSource.Prompt`). After clicking "Select a photo", the user is prompted to provide either limited access, or to allow access to all photos. If the user picks a limited library to share to the app, the photo picker that comes up after this will show the entire photo library regardless. This is causing confusion as the user expects to only see the limited set of photos they selected.

### Expected Behavior

Since `PHPicker` doesn't require an explicit permissions grant to share photos with the app, the user should not see the initial permissions prompt to select a limited photo library. Instead, calling `getPhoto` should only prompt for permissions when necessary, and instead immediately open `PHPicker` in any other case.

### Code Reproduction

Called `Camera.getPhoto` with the following options:

```ts
const cameraPhoto = await Camera.getPhoto({
  quality: 90,
  saveToGallery: true,
  resultType: CameraResultType.DataUrl,
  source: CameraSource.Prompt,
  webUseInput: true,
});
```

### Additional Context

https://developer.apple.com/documentation/photokit/delivering_an_enhanced_privacy_experience_in_your_photos_app

**Comment by jcesarmobile** [comment]
While the `PHPickerViewController` doesn't need the permission to appear, the permission is needed for getting the image information (exif). So that's why the plugin requests the permission.

If the user grants the limited permission, then only the photos that were picked will include the exif information.
Sadly the `PHPickerViewController` doesn't provide a way of only showing the picked images, and also Apple doesn't provide a different picker for only the selected pictures.

The plugin provides the `requestPermissions` method that you can use, and if the users grants the limited access you can then use the `getLimitedLibraryPhotos` method that provides you all the selected photos instead of using `getPhoto`, you can use that to build your own picker if you want.
