### ISSUE TITLE
PushNotifications.getDeliveredNotifications doesn't return FCM `data`

### ISSUE THREAD

**Issue by mahendraHegde** [ionic-team/capacitor-plugins#1302]
### Plugin(s)
```
@capacitor/push-notifications:4.1.1
```

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: unknown
  @capacitor/core: unknown
  @capacitor/android: unknown
  @capacitor/ios: unknown

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0
```

### Platform(s)
```
android
```

### Current Behavior
When I try the below code
```
 const { notifications } = await PushNotifications.getDeliveredNotifications();
```
I receive below payload
```
[
  {
    "id": 0,
    "tag": "FCM-Notification:3123123",
    "title": "test push by dev",
    "body": "dev testing with data",
    "groupSummary": false,
    "data": {
      "android.title": "test push by dev",
      "android.reduced.images": true,
      "android.template": "android.app.Notification$BigTextStyle",
      "android.showChronometer": false,
      "android.text": "dev testing with data",
      "android.progress": 0,
      "androidx.core.app.extra.COMPAT_TEMPLATE": "androidx.core.app.NotificationCompat$BigTextStyle",
      "android.progressMax": 0,
      "android.appInfo": "ApplicationInfo{926aef2 example.app.mobile}",
      "android.showWhen": true,
      "android.bigText": "dev testing with data",
      "android.progressIndeterminate": false
    }
  }
]
```

this is what i'm posting to the FCM api from backend
```
  {
    "android": {
      "priority": "high"
    },
    "notification": {
      "title": "test push by dev",
      "body": "dev testing with data"
    },
    "data": {
      "messageId": "62971793-0111-4c9b-bbb2-bb78262a0543",
      "chatId": "631e162f5f286c23d13e06d5",
      "type": "CHAT_NEW_MESSAGE"
    },
    "token": "fcmToken"
  }
```

So why/how i dont see the data object sent to FCM? I get the data object on events like `pushNotificationReceived` and `pushNotificationActionPerformed`

### Expected Behavior
notifications returned by `PushNotifications.getDeliveredNotifications` call should include data sent from FCM

### Code Reproduction
```
    const { notifications } = await PushNotifications.getDeliveredNotifications();
    console.log({ notifications });
```

**Comment by jcesarmobile** [comment]
Sadly not all data sent from FCM is available through the getDeliveredNotifications API, the native class that the API gets is a [StatusBarNotification](https://developer.android.com/reference/android/service/notification/StatusBarNotification), which as you can check, doesn't have a data parameter nor a method to get the data.
In the "data" object we return all the information that is available.

The custom data you send is only available through the intent associated to the notification, and we can only get the intent once it's launched (on notification click in example), so that's why the data is available on `pushNotificationReceived` and `pushNotificationActionPerformed`
