### ISSUE TITLE
splash-screen: fadeOutDuration not working on Android

### ISSUE THREAD

**Issue by nijakobius** [ionic-team/capacitor-plugins#1322]
### Plugin(s)
@capacitor/splash-screen@4.1.2

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1
```

### Platform(s)
Android (all Versions).

### Current Behavior
When I use `Capacitor.Plugins.SplashScreen.hide({fadeOutDuration: 6000});` the SplashScreen disappears immediately, possibly with a very short fade.

### Expected Behavior
The SplashScreen should be fading out over 6 seconds.

Or, if this is not possible on Android, the docs should mention that `fadeOutDuration` is iOS-only: https://capacitorjs.com/docs/apis/splash-screen

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by digaus** [comment]
Same issue. Start splash does not respect the `fadeOutDuration` when using android 12 splash screen behaviour. Plugin needs to be refactored because the `fadeOutDuration` is set when showing the splash and not when hiding.

Or we need to add `fadeOutDuration` to the plugin config so it is set inside the `showOnLaunch` method. Default is now always 200ms and causes flickering when we use an app which uses fullscreen options.

**Comment by stevium** [comment]
I have the same, this is really crucial for initial user impression when opening an app for the first time.

**Comment by jcesarmobile** [comment]
On SDK 33 there would be an easy fix by using a global variable for storing the fadeOutDuration and make hide to overwrite the value, but on previous versions the initial value gets retained when declared instead of getting the current value when it's being used.

Refactoring is not going to work neither, if the animation listener is moved elsewhere, then it creates two new issues.
1. The fallback to the legacy splash screen no longer works if the user is still using `AppTheme.NoActionBar` as it's the exit animation listener what fails and allows us to detect that they are using the old splash theme parent.
2. On Android < 31 it uses a default android icon instead of the splash screen icon for the animation

So I think best option would be to add a new `launchFadeOutDuration` config option.

**Comment by NePheus** [comment]
> Default is now always 200ms and causes flickering when we use an app which uses fullscreen options.

Good to know where our flickering come from :) then this is the same issue we have. And I thought I made a misstake somewhere.

**Comment by digaus** [comment]
> On SDK 33 there would be an easy fix by using a global variable for storing the fadeOutDuration and make hide to overwrite the value, but on previous versions the initial value gets retained when declared instead of getting the current value when it's being used.
> 
> Refactoring is not going to work neither, if the animation listener is moved elsewhere, then it creates two new issues.
> 
> 1. The fallback to the legacy splash screen no longer works if the user is still using `AppTheme.NoActionBar` as it's the exit animation listener what fails and allows us to detect that they are using the old splash theme parent.
> 2. On Android < 31 it uses a default android icon instead of the splash screen icon for the animation
> 
> So I think best option would be to add a new `launchFadeOutDuration` config option.

Happy new year :) 

Yeah thats what I currently also did locally.  Maybe also completely remove the animation when it is set to 0 ?

**Comment by jcesarmobile** [comment]
can you give https://github.com/ionic-team/capacitor-plugins/pull/1393 a try?

**Comment by NePheus** [comment]
I just tested it and with setting launchFadeDuration to 0, the initial flickering is gone! Thank you very much! 

Is it possible for you to create a nightly release in npm?

**Comment by george-martinec** [comment]
This does not solve the issue with Animated Vector Drawable.

Looks like an Android bug. References:

- https://github.com/aparajita/capacitor-splash-screen/issues/7
- https://github.com/apache/cordova-android/issues/1514
