### ISSUE TITLE
Geolocation: Return values when method fails

### ISSUE THREAD

**Issue by aanders77** [ionic-team/capacitor-plugins#1326]
### Plugin
Geolocation

### Description
I can't find anywhere in the documentation what value to expect if Geolocation.getCurrentPosition() fails.

### Platform(s)
All

### Preferred Solution
Update docs

**Comment by jcesarmobile** [comment]
All the plugins return promises.
If everything went ok, they resolve the promise with the plugin data.
If something fails they reject the promise with a javascript `Error`. So you can get the failure reason with `error.message`.
This is not documented because that's how javascript promises work.
The possible messages are also not documented because most times they come directly from the native message which is not documented by Apple/Google, so we just forward it.
