### ISSUE TITLE
Camera: Consolidate path and webpath into just one property

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/capacitor-plugins#135]
### Plugin
Camera

### Description
Currently, after capturing a photo with `Camera.getPhoto` and using option `CameraResultType.Uri`, the Camera plugin sets `path` to the full, platform specific file URL if executed on mobile (`webpath` is blank), but `webpath` if running on the web (`path` is blank). Instead, consider making it use the same property on all platforms: `path`.

### Platform(s)
web, ios, android

### Preferred Solution
To make this more "cross-platform" friendly, consolidate to just one property: `path`, regardless of platform.

**Comment by jcesarmobile** [comment]
on iOS and Android it returns both `path` and `webPath`. 
`path` is the actual path of the physical file.
`webPath` is a path users can use as source on img/video/audio tags or fetch/XHR. It's the "web friendly" path, to avoid users using convertFileSrc.

On web there is no physical file stored when a picture is taken, so that's why `path` is empty. `webPath` returns a blob url that can also be used on img/video/audio tags or fetch/XHR.

If you say that `webpath` is blank, that's a bug, what's the Capacitor version you used?

**Comment by dotNetkow** [comment]
Just retested and you are correct - webPath is filled in on mobile. Excellent! This code goes back to the Capacitor 1 days, so it must have been updated along the way and I missed that. Thanks, Julio.

I suppose placing the same value into `path` and `webPath` would be nice on the web, but it makes sense why it's blank. Honestly I think this is something we could document better in the Camera docs. I'll make a note and do that for Cap 3.

**Comment by dotNetkow** [comment]
OK, the actual "problem" is that I'd love for FileSystem.read to be able to read the `webPath` on the web. here's what I have to do today, detect platform and run different logic:

```
// Read camera photo into base64 format based on the platform the app is running on
  private async readAsBase64(cameraPhoto: CameraPhoto) {
    // "hybrid" will detect Cordova or Capacitor
    if (this.platform.is('hybrid')) {
      // Read the file into base64 format
      const file = await Filesystem.readFile({
        path: cameraPhoto.path
      });

      return file.data;
    }
    else {
      // Fetch the photo, read as a blob, then convert to base64 format
      const response = await fetch(cameraPhoto.webPath!);
      const blob = await response.blob();

      return await this.convertBlobToBase64(blob) as string;  
    }
  }
```

When it'd be cool to just have it work on all platforms. new issue ticket maybe?
```
// works on web, ios, android
private async readAsBase64(cameraPhoto: CameraPhoto) {
      // Read the file into base64 format
      const file = await Filesystem.readFile({
        path: cameraPhoto.path
      });

      return file.data;
    }
```

**Comment by jcesarmobile** [comment]
> Just retested and you are correct - webPath is filled in on mobile. Excellent! This code goes back to the Capacitor 1 days, so it must have been updated along the way and I missed that. Thanks, Julio.

No, it's been like that since Capacitor 1 on iOS and Android. For web `CameraResultType.Uri` was not supported on v1, was added latter, but don't remember exactly when.

> OK, the actual "problem" is that I'd love for FileSystem.read to be able to read the `webPath` on the web. here's what I have to do today, detect platform and run different logic:

you should be able to fetch/XHR the webPath on all platforms instead of using Filesystem plugin (fetch might not work on iOS if the url contains the custom scheme because of fetch API restrictions, but XHR works for sure)
