### ISSUE TITLE
Implement setOverlaysWebView for iOS

### ISSUE THREAD

**Issue by brilliantinsane** [ionic-team/capacitor-plugins#1385]
### Plugin

Capacitor Status-Bar: https://capacitorjs.com/docs/apis/status-bar

### Description

As of right now calling `setOverlaysWebView` on iOS platform will execute `call.unimplemented()`. I'm wondering why is it like that even now in version 4? Will it ever be implemented? 

### Platform(s)

iOS

**Comment by jcesarmobile** [comment]
Because Apple doesn't provide any API for doing it.
What Cordova plugin does is to resize the WebView to not cover the Status bar area, which is error prone.
By the time it was implemented for Cordova it made sense as it was trying to mimic what iOS < 7 did when iOS 7 came out, but when Capacitor was launched there were web alternatives to avoid the status bar area using css.

https://webkit.org/blog/7929/designing-websites-for-iphone-x/
