### ISSUE TITLE
bug: Device.getInfo() returns wrong device name in `name` prop

### ISSUE THREAD

**Issue by usmanniqbal** [ionic-team/capacitor-plugins#1389]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[error] Main activity file (MainActivity.java) is missing in
        /Users/usman/Developer/onsite/platforms/android/app/src/main/java/com/eventmobi/onsite
```

### Platform(s)

iOS/Android

### Current Behavior

(await Device.GetInfo()).name returns model (probably, on iOS it show `iPhone` on Android (Vivo V23e) it shows `V1161`. whereas correct values are `Usman's IPhone` and `vivo v23e`. Check snapshots).

<img width="414" alt="image" src="https://user-images.githubusercontent.com/16915586/209025725-cae38118-1b8a-469e-ab23-33901e422ee0.png">

![image](https://user-images.githubusercontent.com/16915586/209025855-3d2c6709-2093-4d61-8024-f956f58a7822.png)

### Expected Behavior

Should return Device Name

### Code Reproduction

```
const deviceInfo = await Device.getInfo();
console.log(deviceInfo.name);
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
iOS 16 no longer allows to get the device name unless you add a special entitlement you have to request to Apple and it's not guaranteed that they will give it to you, you have to meet some criteria
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_device-information_user-assigned-device-name

On Android it's working fine for me, can you provide more information about your device? Android OS version (the screenshot shows Funtouch 12, is that Android 12? something else?
Could be a bug on that distribution since it's not the official one.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
