### ISSUE TITLE
Google Maps disappear when tab has changed with Ionic

### ISSUE THREAD

**Issue by epitomz** [ionic-team/capacitor-plugins#1402]
### Plugin(s)

"@capacitor/google-maps":` "^4.3.2"

### Capacitor Version

```
"@capacitor/app": "4.1.1",
"@capacitor/core": "4.6.2"
"@capacitor/ios": "4.6.2"
 "@ionic/angular": "^6.1.9"
```

### Platform(s)

iOS

### Current Behavior

I use Ionic and capacitor to display Google Maps. I put a map in a tab component. First display is totally fine but when the tab page is changed, the map component doesn't display anymore without any arror. The only solution I found is to use `forceCreate: true` in the `GoogleMap.create()`method.

### Expected Behavior

Map should be displayed exactly as it was before changing tab.

### Code Reproduction

You can find the repository to reproduce that behivour [here](https://github.com/epitomz/ionic-google-maps).
You must replace the Google Maps API key in the environment file.

**Comment by metinjakupi** [comment]
Any news?

**Comment by kisimediaDE** [comment]
Same issue

**Comment by sjdrew** [comment]
also same issue really makes this plugin unusable. The forceCreate also did not resolve for me most of the time.

**Comment by SlobodanMarkovic1983** [comment]
Agree. This plugin is completly unusable at the moment. It has so many bugs, so user experience is very bad. Ionic/capacitor team, please make it at least work and then concentrate on other small bugs and features.
List of bugs:
1. Transparency issue in Android
2. Web doesn't show half of the features (eg. pin color, current location, etc)
3. iOS is just awful, almost none of the features work and it has HUGE issue with hidding a map view after you do so many things on the page (navigate away, render something on the current page in DOM, etc)

Please make it at least work on iOS, forget about other things at the moment. I mean I really don't understand how did you tested this and let it go live when it's completly bugged.

**Comment by SlobodanMarkovic1983** [comment]
Basically it happens every time when I load a new page. iOS automatically destroys the map layout view (probably for a good reason). I'm opened for every assistance you need to fix this. Thanks.

**Comment by jonesdhtx** [comment]
This google-maps plugin is unusable for iOS because of this issue  :-( 
Does no one else use this plugin, are we the only ones?

They should take this plugin off their website ASAP since it doesn't work. Other official plugins seem to be high quality and work. I don't know what happened here.

Sad too, b/c reading this blog post they were claiming it was going to be maintained, high quality, etc:
https://ionic.io/blog/announcing-the-capacitor-google-maps-plugin

<img width="772" alt="image" src="https://github.com/ionic-team/capacitor-plugins/assets/385594/010c3281-602d-4d6a-8376-5ffd6179b31b">

What other options are out there for supporting maps in capacitor apps?

**Comment by chvonrohr** [comment]
We use it in production, basically working around that issue. You can re-render the map on every page enter. We store viewport (zoom and position) on change and also take this and markers into account when re-rendering...
