### ISSUE TITLE
[Question] Is it possible to use plugin logic inside another plugin?

### ISSUE THREAD

**Issue by WoodyWoodsta** [ionic-team/capacitor-plugins#1622]
I'm writing a plugin which accesses the filesystem in a way which differs from `@capacitor/filesystem`. However, I'd like to keep the logic for mapping the `Directory` enum in TS to the path on each platform consistent between my plugin and that in `@capacitor/filesystem`.

Is there a way to import `CapacitorFilesystem` into my custom plugin?

I've tried adding it as a pod, and importing it in Swift. Building the plugin itself does not produce any errors, but using the plugin in a Capacitor project leads to an error "Cannot find CapacitorFilesystem".

**Comment by jcesarmobile** [comment]
Please, don't use github issues to ask questions, just to report issues.
For questions you can ask on the [forum](https://forum.ionicframework.com/c/capacitor/26), [discord](https://ionic.link/discord), or the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository.

Capacitor only syncs plugins that are in the app's package.json, so you probably need to install the filesystem plugin in your app too, and instead of using the plugin from CocaPods, you should probably install it from npm as a dev dependency to your plugin and add the dependency in your plugin's Podfile to point to node_modules, something like `pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'`

**Comment by WoodyWoodsta** [comment]
Apologies - I was not aware of the discussions section on them main repo.
