### ISSUE TITLE
feat: opt-out of the use of the Android 12 splash screen API

### ISSUE THREAD

**Issue by javimolla** [ionic-team/capacitor-plugins#1675]
### Plugin
Splash screen

### Description
With the use of the Android 12 API, there are cases where the splash screen is not displayed. It would be interesting to add a method to avoid using this API in some applications that target these devices.

### Platform(s)
Android

### Preferred Solution
Enable to opt-out of the use of the Android 12 splash screen API with a new config keyword. I'm working on this solution and I'll add a pull request later.

### Additional Context
In the [documentation](https://capacitorjs.com/docs/apis/splash-screen) of the plugin, there is a note explaining that the splash screen does not show if launched from some specific ways. Google has solved it for Android 13 but not for 12, so it is never going to work on those devices unless we avoid using the new API.

**Comment by jcesarmobile** [comment]
It's already possible to opt out of the Android 12 splash screen on Android 11 and older devices by setting the splash screen theme parent to `parent="AppTheme.NoActionBar"`.

But it's not possible to opt out of the Android 12 splash screen on Android 12 or newer, it's part of the Android OS, even if you don't install the splash screen plugin a splash screen will appear (except for the cases where it doesn't appear because of the Android 12 bugs). Adding a way of showing the legacy splash screen for Android 12 and newer will cause a duplicate splash screen.

**Comment by javimolla** [comment]
The solution I propose is to avoid calling `showWithAndroid12API` on `SplashScreen.showOnLaunch`. It is useful on those devices with Android 12 bugs.

Anyway, thanks.
