### ISSUE TITLE
@capacitor/filesystem doesn't list files when using readdir

### ISSUE THREAD

**Issue by ZioCain** [ionic-team/capacitor-plugins#1784]
### Plugin(s)
@capacitor/filesystem

### Capacitor Version

   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/core: 5.3.0

[success] Android looking great! 👌

### Platform(s)

I'm testing on Android/Emulator from a Windows computer

### Current Behavior

When I run the following code (changeing the directory option won't change the result) I only get the list of directories in the given folder, but no file (I checked through adb shell and in that specific folder there are both files ad directories)

     Filesystem.readdir({
			path: '/sdcard/',
			//directory: Directory.ExternalStorage
		}).then((res:ReaddirResult)=>{
			console.log("FILESLIST: "+JSON.stringify(res.files, null, 4));
		}).catch((err:any)=>{
			console.error("FILELISTERR "+JSON.stringify(err, null, 4));
		})

### Expected Behavior

I expect to have a list of both directories and files

### Code Reproduction

Basic ionic-capacitor project, no extra settings.
Install the filesystem plugin
Run the code shown above on a button click and see the results
https://github.com/ZioCain/FileReaderSample

### Other Technical Details

Android stated the permissions were granted, so it's not the issue.
Android sdk version is 34, on emulator, debug app

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ZioCain** [comment]
I created this repository to show what and how I'm doing the things.

As stated in the repo, I can't get to read files that are in the given directories

https://github.com/ZioCain/FileReaderSample

**Comment by jcesarmobile** [comment]
Sadly the only way of creating a file browser that works on all android versions would be to request `MANAGE_EXTERNAL_STORAGE` permission, but that's a dangerous permission that would cause app rejections if your app is not a file browser, so it's not something we will be adding to the filesystem plugin, users who need that permission can request it themselves with their own plugin.

Without that permission, the app should work in Android 9 and older, but you are missing the old storage permissions
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
and the code for requesting them `Filesystem.requestPermissions();`
On Android 10 it won't work unless you add this to the application tag of `AndroidManifest.xml` `android:requestLegacyExternalStorage="true"`. 
And on Android 11 or newer, while it seems to list folders just fine, it will only list files your app has created, so that's why the files are not being listed.

We have the behavior documented for the directories we provide, but not for when not using a directory as in your sample app, we should document that too.

**Comment by ZioCain** [comment]
Thank you very much for the details!
I'm not planning on release this app as it's an experiment.
I know android messed permissions up with the latest releases and it's no easy to keep up.

I'd close the issue for the moment.
