### ISSUE TITLE
Lottie Splash

### ISSUE THREAD

**Issue by ebofi** [ionic-team/capacitor-plugins#1821]
## Feature Request
- Can we add Lottie Splash .json files , so that we can set those as splash screen, Is that possibe

**Comment by jcesarmobile** [comment]
Lottie Splash screens need a separate activity, which is discouraged by google since Android 12.
On Android 12 and newer the OS will always show the system splash screen, that you'll have to hide it as fast as you can and then show the lottie splash screen activity.
There [is this cordova plugin](https://github.com/timbru31/cordova-plugin-lottie-splashscreen) that you can use, but as I said, for Android 12 and newer users will have a bad experience with the double splash screen.
