### ISSUE TITLE
App does not wait for user permission to READ and WRITE.

### ISSUE THREAD

**Issue by jocafi** [ionic-team/capacitor-plugins#315]
### Plugin(s)

```
 Filesystem 
```

### Capacitor Version

```
  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
```

### Platform(s)

```
Samsung S20, Android 11.
```
### Current Behavior

```
The app does not wait for the user input to allow or not the permission to READ and WRITE.
```

### Expected Behavior
```
The app waits for the user input to allow or not the permission to READ and WRITE.
```

the app does not wait for the user allow or not the permission.

### Code Reproduction

```
Filesystem.requestPermissions().then(() => log.info('Directory permissions: PASSED'),
      error => {
        log.error('Directory permissions: FAILED. Error: ', error);
        this.route.navigateByUrl('/error-page');
      }).catch(error => {
      log.error('Directory permissions: FAILED. Error: ', error);
      this.route.navigateByUrl('/error-page');
    });
```

### Other Technical Details

I am trying to use the Filesystem from Capacitor v. 3.0.0-rc.0, but the app fails to start, because I need to load a config file at the beginning and the app does not wait user input to allow or not the permission to READ and WRITE.

I am using a Samsung S20, Android 11.
I added **android:requestLegacyExternalStorage="true"** to my <application> tag in the AndroidManifest.xml file as described in the documentation.

I tried to use the plugin for android-permissions but I get an error:
```
NullInjectorError: No provider for AndroidPermissions!
```

In order to reproduce the error I had to uninstall and install the app again.

**Comment by jcesarmobile** [comment]
Please, provide a sample app where the problem can be reproduced.

**Comment by jocafi** [comment]
Here is the sample:  https://github.com/jocafi/ionic5-test

**Comment by jcesarmobile** [comment]
The problem is you are trying to read the folder outside the promise result, so the read code is executed while the prompt is present and makes it return an error.
It's a know issue https://github.com/ionic-team/capacitor-plugins/issues/320

But the workaround is simple, wait for the permissions result before trying to call other filesystem methods.

**Comment by jocafi** [comment]
Move the code that "read the folder" inside the promise for Filesystem.requestPermissions(). The permission dialog will never be shown.

**Comment by jcesarmobile** [comment]
requestPermission resolves once the user accept or deny the prompt, so the code inside the requestPermission .then is executed.
The permission dialog is shown by requestPermission, the problem in your app is the read folder code triggers another prompt, but as one is already shown it gets canceled, and by the issue I linked, the first promise gets rejected instead of the second one.
