### ISSUE TITLE
push-notifications types are incomplete

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#350]
### Plugin(s)
push-notifications

### Capacitor Version
3.x

```
PASTE OUTPUT HERE
```

### Platform(s)
all

### Additional Context

A lot of fields on push notifications plugin types don't have a description, some of them such as "notification", are android only and it's not mentioned on the description.

**Comment by uncvrd** [comment]
Adding to this, there seems to be a discrepancy between typings on `ActionPerformed`'s notification typing called `PushNotificationSchema` located [here](https://github.com/ionic-team/capacitor-plugins/blob/d97898662d0ba037e5f8448990a91de5ec6a4234/push-notifications/src/definitions.ts#L159). For example, it appears that in the swift implementation, some data is added to an `extra` key located [here](https://github.com/ionic-team/capacitor-plugins/blob/d97898662d0ba037e5f8448990a91de5ec6a4234/push-notifications/ios/Plugin/PushNotificationsHandler.swift#L86). However I think this was meant to be called `data` instead of `extra` because the Android implementation adds this dictionary to the `data` key instead (located [here](https://github.com/ionic-team/capacitor-plugins/blob/d97898662d0ba037e5f8448990a91de5ec6a4234/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java#L72)) which would then match the Typescript definition

**Comment by jcesarmobile** [comment]
That’s already fixed on latest commit, but still unreleased

**Comment by uncvrd** [comment]
Ok good to know thank you!
