### ISSUE TITLE
bug(clipboard) Clipboard.write error "Clipboard API not available in this browser" using native iOS Safari

### ISSUE THREAD

**Issue by uncvrd** [ionic-team/capacitor-plugins#354]
### Plugin(s)

- `@capacitor/clipboard: ^0.4.6`

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/core 3.0.0-rc.0
  @capacitor/electron not installed
```

### Platform(s)

- NATIVE iOS Safari browser (not emulator)

### Current Behavior

Using `Clipboard.write()` from a native iOS Safari Browser causes the following error:

`Unhandled Rejection: Clipboard API not available in this browser`

the `write` method works excellently on the native build of an iOS app, but when using the web version on an iOS Safari browser, I encounter the above error.

Video recreation: https://streamable.com/21f40t

### Expected Behavior

I expect to be able to copy to clipboard using `Clipboard.write()` on iOS Safari without an unhandled exception error.

### Code Reproduction

Code for reproducing: https://github.com/uncvrd/capacitor-file-upload-button (using same repo for another bug I just posted)

- Make sure to run: `ionic serve --external -l` so that you can run the application on your mobile device using the the local IP the cli shows
- Using your iOS safari browser, route to the ip where this app is running
- Click "Copy to Clipboard"

### Other Technical Details

It's interesting to note that I cannot emulate this using iOS emulator on my computer, it has to be on a physical device to recreate this problem!

**Comment by jcesarmobile** [comment]
On iOS the web clipboard API only works on https context

**Comment by uncvrd** [comment]
@jcesarmobile hi - could you clarify a little more about this? I don't see anything mentioned about the restrictions in documentation [here](https://capacitorjs.com/docs/v3/apis/clipboard) and I'm fairly certain this was working on Capacitor 2.0.  Are you saying that the only method that will work when using mobile safari is the `url` object option within the `write` method?

**Comment by jcesarmobile** [comment]
We just do a `navigator.clipboard` check, if it's there we use it, if it's not there, we can't use it and throw that error, so if you get the error it's because it's not there.

In my tests it wasn't there on http, but was on https.
We don't put the restrictions, it's Apple who controls what requires a secure context and what not, best thing we can do is to throw an error when it's not available. We do it in all plugins, if the browser API that the plugin uses is not available we throw an error, but we don't document in which browsers it works because we don't know.

This webkit links mentions that it requires a secure context.
https://webkit.org/blog/10855/async-clipboard-api/
