### ISSUE TITLE
feat: React Native bridge for plugins

### ISSUE THREAD

**Issue by D-Marc1** [ionic-team/capacitor-plugins#420]
### Description

I love using Capacitor and I think it was a great idea to make most Cordova plugin backwards compatible, but  even better, would be a way to create a bridge to make React Native plugins work on Capacitor. The React Native ecosystem always makes me jealous and I really wish there could be a way to automagically make this work eventually for Capacitor.

**Comment by jthoms1** [comment]
What are some of the plugins that make you jealous? Genuinely interested.

**Comment by D-Marc1** [comment]
@jlane9 There's many, but just to name a few:

https://github.com/Michaelvilleneuve/react-native-document-scanner

https://github.com/HarvestProfit/react-native-rectangle-scanner

https://github.com/birkir/react-native-carplay

https://github.com/viromedia/viro

I honestly think there's a better ecosystem in Rect Native, than native iOS and Android even.

**Comment by jcesarmobile** [comment]
there is already another issue about in in capacitor repository (which makes more sense there since the changes should be done in capacitor internals, not in our plugins). https://github.com/ionic-team/capacitor/issues/3371
So closing this one

Anyway, I don't think it's a feasible feature, but would be happy if somebody proves I'm wrong by sending a PR that makes it possible.

**Comment by D-Marc1** [comment]
My apologies, didn't notice that. Couldn't find it when I tried to google it. It seems possible in theory (though very challenging), but just seems like it would be a ton of work.
