### ISSUE TITLE
bug: ClassCastException in NotificationStorage

### ISSUE THREAD

**Issue by MedaiP90** [ionic-team/capacitor-plugins#434]
### Capacitor Version

```
@capacitor/cli 2.4.0
@capacitor/android 2.4.0
@capacitor/core 2.4.0
@capacitor/ios 2.4.0
```

### Platform(s)

Android

### Current Behavior

Analyzing play store's crash reports it came out that a `ClassCastException` occurs in `NotificationStorage.getSavedNotificationAsJSObject` at **LocalNotificationRestoreReceiver.java:31**

![Screenshot_2020-09-20-17-05-23-899_com google android apps playconsole](https://user-images.githubusercontent.com/20813764/93741028-f4225b00-fbeb-11ea-8745-dc808e7b8e87.jpg)

### Expected Behavior

No exception should occur.

### Other Technical Details

`npm --version` output: `6.14.6`

`node --version` output: `v12.18.4`

**Comment by tgangso** [comment]
Still getting this on capacitor version 3. Is this related to LocalNotifications.getPending() ?

**Comment by kirillgroshkov** [comment]
Yep, real issue, happens to us too.

**Comment by sSarahlei** [comment]
I figured out this issue is happening on device reboot when there are pending local notifications.
A case where it could happen is if there is a pending local notification that was received on an app that has capacitor version<2.3.0, then the app auto-updated (or manually updated, and then the device was shut downn) to a version that includes capacitor version > 2.3.0, and device was restarted.
Capacitor is trying to retrieve the pending local notifications and display them.
see changelog https://github.com/ionic-team/capacitor/blob/2.x/CHANGELOG.md#230-2020-07-16
-> commit: https://github.com/ionic-team/capacitor/commit/2a39a7d.

Previously, Capacitor used to store local notifications ids and long , and with that change its storing it as string.
So on device reboot, when trying to retrieve the pending local notification there is a classCastException.
From my experience the crash isn't displayed on new android version (android 10, and 11) and hasn't affected my app behavior.
