### ISSUE TITLE
EXIF Data Stripped From Images 

### ISSUE THREAD

**Issue by jczaplew** [ionic-team/capacitor-plugins#45]
When using the camera plugin on both Android and iOS most or all EXIF data is stripped from the image. On Android all attributes are stripped, and on iOS only `Orientation`, `ExifIFDPointer`, `ColorSpace`, `PixelXDimension` and `PixelYDimension` are returned.  

I could see this being handled in the following ways:

   A) Return an EXIF dictionary with the image path
   B) Retain the original EXIF data on the image itself

I think providing both is ideal, as A) would allow the client to use the EXIF data without needing to use a third-party library for using the EXIF data within the app. Additionally, B) allows for a direct upload for server-side parsing without needing to write the EXIF data back to the image client-side. 

I am using the following code to test this:

````javascript
import { Plugins, CameraResultType, CameraSource } from '@capacitor/core'
const { Camera } = Plugins
import { EXIF } from 'exif-js'



async getPhoto() {
    const image  = await Camera.getPhoto({
       quality: 100,
       correctOrientation: true,
       resultType: CameraResultType.Uri,
       source: CameraSource.Prompt
    })

    EXIF.getData({ src: image.webPath }, function(error) {
        if (error) {
          console.log(error)
        }
        var allMetaData = EXIF.getAllTags(this);
        console.log('ALL TAGS - ', allMetaData)

        let lng = EXIF.getTag(this, 'GPSLongitude') || null
        let lat = EXIF.getTag(this, 'GPSLatitude') || null

        console.log('LNG - ', lng)
        console.log('LAT - ', lat)
    })
  }
````

I don't have experience writing Swift or Java, but if there is anything I can do to help implement this please let me know!

**Comment by sebastianovide** [comment]
@jarek104 have you found a workaround until when it is merged in capacitor ?

**Comment by davidofwatkins** [comment]
Was this meant to be closed? I see this has been fixed on Android above, but I'm still not able to get GPS EXIF data when taking a photo on iOS.

Unfortunately the plugin has changed significantly since the workaround posted above, and I lack the Swift/iOS knowledge to apply it to the latest version.

**Comment by jthoms1** [comment]
@davidofwatkins Are your issues on Capacitor 2 or do they persist in Capacitor 3?

**Comment by davidofwatkins** [comment]
@jthoms1 I have only tried this on Capacitor 3, unfortunately (iOS 14.5)

**Comment by dtarnawsky** [comment]
@davidofwatkins GPS EXIF data is not captured when accessing the Camera plugin. This is because the camera plugin does not obtain the location of the device. To capture location information you will need to do this yourself by adding the geolocation plugin, capturing the current location (before or after capturing the photo) then using this along with the image captured. 

Note that the Camera app in iOS and Android both request geolocation permissions and capture location information and will include it in the EXIF of photos that are saved. This is why you see this data in photos you have selected from the photo library.

This particular issue on Cap 2 and 3 was causing all the other EXIF data to not save.
If you would like more detailed information on this it is worth looking at this repo:
[https://github.com/dtarnawsky/capacitor-exif-test](https://github.com/dtarnawsky/capacitor-exif-test)
