### ISSUE TITLE
appStateChange fired too late

### ISSUE THREAD

**Issue by no-creative-name** [ionic-team/capacitor-plugins#479]
### Plugin(s)
@capacitor/app

### Capacitor Version
@capacitor/cli: 3.0.1
@capacitor/android: 3.0.1
@capacitor/core: 3.0.1
@capacitor/ios: 3.0.1

### Platform(s)
Android

### Current Behavior
Since for our app security/data privacy is a huge factor, we need to implement a way that the app content is hidden (white screen) when the app is backgrounded (e.g. in the task manager). For this is wanted to use the "appStateChange" event listener from @capacitor/app. The problem is that the event only fires when coming back into the app after putting it into the background. This makes it unusable for our use case. 

### Expected Behavior
"appStateChange" also fires before/when the app is backgrounded.

### Other Technical Details
Tested on a real Android device and a simulated one.

**Comment by no-creative-name** [comment]
I found https://github.com/capacitor-community/privacy-screen to be able to hide the screen in the task manager. Still I think this should work as expected.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by shpasser** [comment]
This issue does not need any more information.

In order to reproduce the issue just build an Android app using the plugin and use the supplied example:

```
import { App } from '@capacitor/app';

App.addListener('appStateChange', ({ isActive }) => {
  console.log('App state changed. Is active?', isActive);
});
```

While debugging the app enable the debug console in Android Studio and look for `App state changed. Is active?` and you will see that only the `resume` events are handled.

In order to reproduce the `pause/resume` behavior just leave and re-enter the app on your phone.

The behavior in Android is buggy while in iOS it works as expected.

**Comment by shpasser** [comment]
I think that the actual issue is here:

https://github.com/ionic-team/capacitor/blob/ee2069a6e9d3d52e232a31d35909faf87c272c7c/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java#L91

The function should call `bridge.getApp().fireStatusChange(false);` but it doesn't.

**Comment by jcesarmobile** [comment]
Sorry, but I can't reproduce.
the event is being fired on onStop, not on onPause, that's why the code is not on that line, but it's being fired on my app.

There is an feature request open for including more states so it could be fired on pause.

Also, for Cordova compatibility we also fire the cordova pause event, you can use it like this: `document.addEventListener("pause", yourCallbackFunction, false);`
