### ISSUE TITLE
replace getCurrentPosition logic

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#571]
### Plugin
geolocation

### Description
replace getCurrentPosition logic to use fusedLocationClient.getCurrentLocation

### Platform(s)
android

### Additional Context

it's breaking because it doesn't allow to configure the timeout, it will always be 10 seconds max

seems to solve
https://github.com/ionic-team/capacitor/issues/4962

**Comment by maslaw** [comment]
Hello @jcesarmobile 
Thank you very much for your help with this issue
I can see that your PR https://github.com/ionic-team/capacitor-plugins/pull/589 is merged now.

Sorry, could you tell please, when can we update our Capacitor projects to get this fix? I started using Capacitor 3 months ago, so don't know how much time it usually takes. But my Android app is already released, that's why I decided to ask you about it.

Thank you very much

**Comment by jcesarmobile** [comment]
I don't do the releases, so I'm not sure.
We usually do releases every two weeks and last one was two weeks ago, so it might be out today, but no promises.

**Comment by jcesarmobile** [comment]
this has been fixed in 4.0.0 beta 0
