### ISSUE TITLE
feat:  ClearCache on Browser

### ISSUE THREAD

**Issue by Invictorius** [ionic-team/capacitor-plugins#7]
### Description
Make more Browser Options

I use Capacitor Brower to make a Authentication Service, it's work fine, but without a clearCache, when an user logged is opening the auth link, the user is connected directly without the possibility to connect with another account 
Could be nice to have

### Platform(s)
Android
iOS

**Comment by thomasvidas** [comment]
The browser plugin uses [SFSafariViewController](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller) on iOS and [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs) on Android. Because these share data with the Safari and Chrome apps, it does not allow us to clear cookies or localstorage or anything else like that unfortunately.

**Comment by dejan9393** [comment]
I am running into the same limitation as mentioned; once logged in, I can't seem to log the user out. What is the recommended solution for removing a login session/cookie?
