### ISSUE TITLE
How to get phone's MAC Address?

### ISSUE THREAD

**Issue by p770820** [ionic-team/capacitor-plugins#70]
### Plugin
Device

### Description
How to get phone's MAC Address?

### Platform(s)
Android 
iOS

**Comment by ikeith** [comment]
The ability to get a phone's MAC address has been blocked for years now because it provided an easy to way uniquely identify a device and therefore track the user so it was prone to abuse.
[Since iOS 7](https://developer.apple.com/library/archive/releasenotes/General/WhatsNewIniOS/Articles/iOS7.html#//apple_ref/doc/uid/TP40013162-SW34)
[Since Android 6](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id)
