### ISSUE TITLE
Is there a local notification limit?

### ISSUE THREAD

**Issue by davidecampello** [ionic-team/capacitor-plugins#723]
Hi, is there a limit on number of local notifications scheduled?

**Comment by thomasvidas** [comment]
I believe on Android there is not a limit, but newer versions may rate limit if you schedule too many in a short period of time.

On iOS you can only schedule 64 notifications due to limits set my Apple.

For future reference, we typically ask people to ask questions like this on the [Ionic forum](forum.ionicframework.com) so it's more easily searchable than GitHub issues 😄

**Comment by davidecampello** [comment]
You're right! I'm sorry
