### ISSUE TITLE
@capacitor/app-launcher Android 11 - scaleable app package names?

### ISSUE THREAD

**Issue by donmb1** [ionic-team/capacitor-plugins#732]
### Plugin
@capacitor/app-launcher

### Description
The Readme declares that it is necessary to add a new app package name whenever it has to be queried. This is a complicated scenario, especially if you want to dynamically add new "links" to apps in your application.

In our usecase the user can create their own links. So whenever the user adds a new link, we would need to update the AndroidManifest?

### Platform(s)
Android 11+

### Preferred Solution
Ideally a wildcard could get declared in `<queries>` which allows to open any app.

```
<queries>
  <package android:name="*" />
</queries>
```

**Comment by jcesarmobile** [comment]
That's an Android restriction imposed by Google, not us, there is nothing we can do about it. We just document that it's necessary because it won't work if you don't add it.
The plugin doesn't read the value, but the calls to the native API fails if not included.

https://developer.android.com/guide/topics/manifest/queries-element
