### ISSUE TITLE
Support for Huawei Mobile Services

### ISSUE THREAD

**Issue by WayneKruger** [ionic-team/capacitor-plugins#786]
## Feature Request

Capacitor plugins that utilize GMS (Google Mobile Services) to support HMS. 

### Plugin
@capacitor/geolocation
@capacitor/push-notifications

### Description
Currently if you use a plugin that utilizes GMS, your app will not work on the newer HMS-only Huawei devices since they do not support GMS. In some cases the app will not be downloadable in the Huawei App Gallery, in other cases the plugin just wont work.

Huawei does provide Cordova plugins but this means one would still need to implement HMS detection and then switch accordingly. Having this integrated would make things a lot easier. Also having a pure capacitor plugin instead of cordova is preffered.

### Platform(s)
Android

### Preferred Solution
Add in a check if the device supports HMS and then utilize the equivalent HMS plugin

### Alternatives
[Cordova Plugins](https://forums.developer.huawei.com/forumPortal/en/topic/0201267687754350041?fid=0101187876626530001)

### Additional Context
Here

**Comment by jcesarmobile** [comment]
Thanks for the issue, but with Google Services we cover most part of the Android market.
Also, we try to use the minimum number of dependencies possible, and I've been taking a look and HMS requires to get huawei dependencies from huawei maven repositories that some people might not want to connect to and use custom huawei gradle plugins and even their own configuration file that would make the usage of the plugins more complex even if the users are not interested on the HMS part, so I think they should be separate plugins instead of being integrated into our core ones.
You can request community plugins [here](https://github.com/capacitor-community/proposals/issues)

For geolocation, there is [another issue](https://github.com/ionic-team/capacitor-plugins/issues/775) about not using GMS, we might consider to fall back to getting location without any services, but not to use an alternative service.
