### ISSUE TITLE
bug: App 'backButton' listener is triggered by forward gesture

### ISSUE THREAD

**Issue by ford-thomas-w** [ionic-team/capacitor-plugins#833]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

### Platform(s)
Android

### Current Behavior
App.addListener('backButton'   ...   is triggered by a forward gesture on Android when Gesture navigation is enabled in the Settings.  In Pixel 6 Gesture nav is the default.  The setting to change it to use hardware back button is not readily visible.  You must search for the setting.  

### Expected Behavior
This would not be too problematic if it was possible to detect the gesture type from the passed parameter.  However, the "BackButtonListenerEvent" which is passed in, provides no way to differentiate between a forward and back gesture.  So, I would expect 'backButton' event NOT to be triggered by a forward swipe gesture.  Or, at least, I would expect there to be some way to differentiate the two from the passed param.

### Code Reproduction
```
App.addListener('backButton', (evt: BackButtonListenerEvent) => {
    // this is triggered by a forward swipe
    console.log('back button event', evt);
});
```

### Other Technical Details

`npm --version` output: 6.14.13

`node --version` output: v14.17.3

`pod --version` output (iOS issues only):

### Additional Context

Perhaps have a separate event for 'fowardGesture'

**Comment by jcesarmobile** [comment]
Moving to capacitor-plugins repository as that's what handles the back button event.

But this looks like an OS bug to me, this is the code used for handling the back button:
https://github.com/ionic-team/capacitor-plugins/blob/3ec2008bc0311c837346ecbdd0afd105149b427a/app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java#L43-L58

it's fired on `handleOnBackPressed()`, so if it's getting fired with forward navigation it's because forward navigation is firing the native `handleOnBackPressed()` and it provides no information about if it was forward or backward, so I don't think we can do anything about it.

**Comment by jcesarmobile** [comment]
I've reported the issue on google issue tracker, we can't do anything else until they provide a way of differentiating between gestures
https://issuetracker.google.com/issues/247977484
