### ISSUE TITLE
Camera checkPermissions() error in Safari

### ISSUE THREAD

**Issue by kinggolf** [ionic-team/capacitor-plugins#875]
### Plugin
Camera

### Description
Camera.checkPermissions() returns error when running in Safari, mobile and desktop.

### Platform(s)
Safari 15.4 (desktop) & 15.3 (mobile)

### Preferred Solution
Camera.checkPermissions() should return permission status w/out error.

### Alternatives
None

### Additional Context
Demo repo https://github.com/kinggolf/tutorial-photo-gallery-angular, which was built from https://github.com/ionic-team/tutorial-photo-gallery-angular.

Demo website https://kc.kinggolfapps.com/. Load into safari and inspect to see Camera.checkPermissions() result.

**Comment by jcesarmobile** [comment]
The error I get is `Permissions API not available in this browser`, which is expected because `navigator.permissions` is not available on Safari.
Since you mentioned latest versions of Safari I thought they implemented it in a way that was causing issues with the plugin code, but this has always been like this in Safari and won't work until Apple implements `navigator.permissions`.

Sadly there is nothing we can do about it, there is no other way of checking the camera permission, so we throw an error when the required API is not available, as we do on all plugins.
