### ISSUE TITLE
pushNotificationReceived is not trigger when app is in foreground

### ISSUE THREAD

**Issue by kiranrayala77** [ionic-team/capacitor-plugins#909]
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/android: 3.4.3
  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3

### Platform(s)
Android

### Current Behavior
when the app is in foreground pushNotificationReceived will call as  per documents but its not working

### Expected Behavior
pushNotificationReceived will be triggered

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by kiranrayala77** [comment]
https://github.com/kiranrayala77/notification.git

Issue is. when the app is foreground pushNotificationReceived is not trigerred

**Comment by jcesarmobile** [comment]
You have your own MessagingService service instead of using Capacitor's one. 
If I remove your service from AndroidManifest then it works.

If you want to keep your service, you have to use our PushNotifications plugin, your are using your own, that won't work, you can only have a plugin with the same name, also you are not registering it, Capacitor 3 auto register plugins, but only the ones installed from npm, not custom plugins, you have to register them in MainActivity by calling registerPlugin. But you can't use the same name, if you want to use your own push plugin you'll have to rename it, but also use your plugin listeners not PushNotifications listeners in the js/ts code.

If I remove your PushNotifications class and add `import com.capacitorjs.plugins.pushnotifications.PushNotificationsPlugin;` in your MessagingService so it uses our plugin then it works.

**Comment by kiranrayala77** [comment]
Thanks Ionic-Team/Capacitor-Plugins
