### ISSUE TITLE
Animated Splash Screen

### ISSUE THREAD

**Issue by kpatfln** [ionic-team/capacitor-plugins#935]
### Plugin
@capacitor/splash-screen

### Description
Allow the splash screen plugin to show a series of image files to show an animation on splash screen.

### Platform(s)
iOS, Android

### Preferred Solution
See Description.

### Alternatives
N/A

### Additional Context
N/A

**Comment by matzar** [comment]
That is currently possible on Android 12. You can use the [google's example of the animated splash screen](https://developer.android.com/develop/ui/views/launch/splash-screen#splash-screen-resources) if you'd like to see it working (mark, you'll have to remove the comments from the `news_avd_v02.xml` file - otherwise, the project won't build.

For google's example, in your `android/app/src/main/res/values/styles.xml` file change:

```xml
<style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
        <item name="android:background">@drawable/splash</item>
</style>
```

to

```xml
<style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/news_avd_v02</item>
 </style>
```

You'll also have to add `news_avd_v02.xml` file to `android/app/src/main/res/drawable`.

After doing all that, simply run your android app and you should see the animated splash screen working.

**Comment by benjmo** [comment]
Oops, I forgot #965 was still open in the process of reworking the branching in our fork: https://github.com/freelancer/capacitor-plugins. The `main` branch was changed to be in sync with upstream and as a result, the PR was marked as merged and this issue is incorrectly marked as completed. 

Due to [Splash Screen API changes on Android](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate), I will not re-create the original PR as it no longer works on Android 12+. I think supporting animated splash via capacitor would need a different approach.

The changes that were originally in the PR are viewable here: https://github.com/ionic-team/capacitor-plugins/compare/3.x...freelancer:capacitor-plugins:3.x
